export const customStyles = {
  root: {
    "--bg-color": "#cfb394",
    "--ink-color": "#4A3424",
    "--ink-light": "rgba(74, 52, 36, 0.58)",
    "--font-sans": "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
    "--font-mono": "'JetBrains Mono', 'Courier New', Courier, monospace",
  },
  body: {
    backgroundColor: "#cfb394",
    color: "#4A3424",
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale",
    lineHeight: 1.4,
    overflowX: "hidden",
    cursor: "crosshair",
    minHeight: "100vh",
  },
  sysContainer: {
    width: "100%",
    padding: "1rem 2rem 2rem",
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    position: "relative",
    zIndex: 10,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "1rem",
    fontFamily: "'JetBrains Mono', 'Courier New', Courier, monospace",
    fontSize: "0.75rem",
    textTransform: "uppercase",
    borderBottom: "1px solid #4A3424",
    paddingBottom: "1rem",
    marginBottom: "2rem",
  },
  metaBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
  },
  metaLink: {
    color: "#4A3424",
    textDecoration: "none",
    borderBottom: "1px solid transparent",
    width: "fit-content",
    transition: "border-color 0.15s ease",
  },
  metaLabel: {
    color: "rgba(74, 52, 36, 0.58)",
  },
  hero: {
    position: "relative",
    width: "100%",
    height: "70vh",
    minHeight: "500px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "4rem",
    borderBottom: "1px solid #4A3424",
  },
  asciiCanvas: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    zIndex: 1,
    mixBlendMode: "multiply",
  },
  heroTitle: {
    position: "relative",
    zIndex: 2,
    fontSize: "clamp(4rem, 12vw, 16rem)",
    fontWeight: 500,
    letterSpacing: "-0.04em",
    lineHeight: 0.85,
    textAlign: "center",
    textTransform: "lowercase",
    mixBlendMode: "color-burn",
    pointerEvents: "none",
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
    color: "#4A3424",
  },
  main: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  introBlock: {
    paddingBottom: "1.5rem",
  },
  sectionBlock: {
    width: "100%",
    paddingBottom: "2rem",
    borderBottom: "1px solid rgba(74, 52, 36, 0.25)",
  },
  sectionHeaderRow: {
    display: "flex",
    alignItems: "baseline",
    fontFamily: "'JetBrains Mono', 'Courier New', Courier, monospace",
    fontSize: "0.85rem",
    borderBottom: "1px solid rgba(74, 52, 36, 0.4)",
    paddingBottom: "0.25rem",
    marginBottom: 0,
    cursor: "pointer",
    transition: "background-color 0.15s ease, color 0.15s ease",
  },
  sectionLabel: {
    width: "10rem",
    flexShrink: 0,
  },
  sectionTitle: {
    flexGrow: 1,
  },
  sectionMeta: {
    fontFamily: "'JetBrains Mono', 'Courier New', Courier, monospace",
    textAlign: "right",
    paddingLeft: "1rem",
  },
  sectionContent: {
    paddingTop: "1.5rem",
  },
  h2: {
    fontSize: "1.5rem",
    fontWeight: 500,
    letterSpacing: "-0.02em",
    marginBottom: "1rem",
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
  },
  p: {
    fontSize: "1rem",
    marginBottom: "1.5rem",
    maxWidth: "none",
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
  },
  monoText: {
    fontFamily: "'JetBrains Mono', 'Courier New', Courier, monospace",
    fontSize: "0.85rem",
    lineHeight: 1.6,
  },
  tocList: {
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    padding: 0,
    margin: 0,
  },
  tocItem: {
    display: "flex",
    alignItems: "baseline",
    fontFamily: "'JetBrains Mono', 'Courier New', Courier, monospace",
    fontSize: "0.85rem",
    borderBottom: "1px solid rgba(74, 52, 36, 0.4)",
    paddingBottom: "0.25rem",
    cursor: "pointer",
    transition: "background-color 0.15s, color 0.15s",
  },
  tocNum: {
    width: "3rem",
    flexShrink: 0,
  },
  tocTitle: {
    flexGrow: 1,
  },
  tocPage: {
    textAlign: "right",
    paddingLeft: "1rem",
  },
  sysFooter: {
    marginTop: "4rem",
    paddingTop: "1rem",
    borderTop: "1px solid #4A3424",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1rem",
    fontFamily: "'JetBrains Mono', 'Courier New', Courier, monospace",
    fontSize: "0.75rem",
  },
  footerLink: {
    color: "#4A3424",
    textDecoration: "none",
    borderBottom: "1px solid #4A3424",
  },
  aboutPage: {
    width: "100%",
    minHeight: "100vh",
    padding: "1rem 2rem 2rem",
    display: "flex",
    justifyContent: "flex-start",
  },
  aboutInner: {
    width: "100%",
    maxWidth: "700px",
    display: "flex",
    flexDirection: "column",
    gap: "1.9rem",
    alignItems: "flex-start",
  },
  aboutTitle: {
    fontSize: "2rem",
    fontWeight: 500,
    letterSpacing: "-0.02em",
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
    marginBottom: "0.75rem",
  },
  aboutNav: {
    color: "#4A3424",
    textDecoration: "none",
    borderBottom: "1px solid #4A3424",
    fontFamily: "'JetBrains Mono', 'Courier New', Courier, monospace",
    fontSize: "0.8rem",
    textTransform: "uppercase",
    marginBottom: "1.5rem",
  },
  aboutParagraph: {
    fontSize: "1rem",
    lineHeight: 1.9,
    maxWidth: "58ch",
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
  },
  introPage: {
    width: "100%",
    minHeight: "100vh",
    padding: "1rem 2rem 2rem",
    display: "flex",
    justifyContent: "center",
  },
  introInner: {
    width: "100%",
    maxWidth: "780px",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: "1.2rem",
  },
  introNav: {
    color: "#4A3424",
    textDecoration: "none",
    borderBottom: "1px solid #4A3424",
    fontFamily: "'JetBrains Mono', 'Courier New', Courier, monospace",
    fontSize: "0.8rem",
    textTransform: "uppercase",
    width: "fit-content",
    marginBottom: "1.2rem",
  },
  introTitle: {
    fontSize: "2.5rem",
    lineHeight: 1.1,
    fontWeight: 500,
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
    textAlign: "center",
    marginBottom: "0.75rem",
  },
  introSection: {
    fontSize: "1.35rem",
    lineHeight: 1.2,
    fontWeight: 600,
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
    marginTop: "1rem",
    marginBottom: "0.25rem",
  },
  introParagraph: {
    fontSize: "1.06rem",
    lineHeight: 1.8,
    fontFamily: "'Helvetica Neue', Helvetica, -apple-system, sans-serif",
    textAlign: "left",
  },
};
